/*
Copyright © 2024 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"github.com/spf13/cobra"
)

// endpointsCmd represents the endpoints command
var endpointsCmd = &cobra.Command{
	Use:   "endpoints",
	Short: "Generate a list of all endpoints in the cluster",
	Long: `List all the shards in the cluster including all the fields
generated by rladmin status.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return buildOutput(cmd, clusterInfo.Endpoints)
	},
}

func init() {
	rootCmd.AddCommand(endpointsCmd)
	endpointsCmd.Flags().BoolP("json", "j", false, "output results as JSON")
	endpointsCmd.Flags().BoolP("csv", "c", false, "output results as as CSV")
	endpointsCmd.MarkFlagsMutuallyExclusive("json", "csv")
	endpointsCmd.MarkFlagsOneRequired("json", "csv")
}
