/*
Copyright © 2024 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"github.com/spf13/cobra"
)

// nodesCmd represents the nodes command
var nodesCmd = &cobra.Command{
	Use:   "nodes",
	Short: "Generate a list of all nodes in the cluster",
	Long: `List all the nodes in the cluster including all the fields
generated by rladmin status.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return buildOutput(cmd, clusterInfo.Nodes)
	},
}

func init() {
	rootCmd.AddCommand(nodesCmd)
	nodesCmd.Flags().BoolP("json", "j", false, "output results as JSON")
	nodesCmd.Flags().BoolP("csv", "c", false, "output results as as CSV")
	nodesCmd.MarkFlagsMutuallyExclusive("json", "csv")
	nodesCmd.MarkFlagsOneRequired("json", "csv")
}
