/*
Copyright © 2024 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"github.com/spf13/cobra"
)

// shardsCmd represents the shards command
var shardsCmd = &cobra.Command{
	Use:   "shards",
	Short: "Generate a list of all shards in the cluster",
	Long: `List all the shards in the cluster including all the fields
generated by rladmin status.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return buildOutput(cmd, clusterInfo.Shards)
	},
}

func init() {
	rootCmd.AddCommand(shardsCmd)
	shardsCmd.Flags().BoolP("json", "j", false, "output results as JSON")
	shardsCmd.Flags().BoolP("csv", "c", false, "output results as as CSV")
	shardsCmd.MarkFlagsMutuallyExclusive("json", "csv")
	shardsCmd.MarkFlagsOneRequired("json", "csv")
}
